### ISSUE TITLE
Create a function to map ethnicity from rate to data

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/vivarium_population_spenser#19]
Using the lookup table, create a function that gives the same ethnicity nomenclature than the rates https://github.com/alan-turing-institute/vivarium_public_health_spenser/blob/master/persistant_data/ethnic_lookup.csv

**Comment by kasra-hosseini** [comment]
PR: https://github.com/alan-turing-institute/vivarium_public_health_spenser/pull/20
