### ISSUE TITLE
Build an Emigration module

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/vivarium_population_spenser#28]
- [x] Start from the Mortality component and write a new Emigration component that implements emigration based on rates from (#27 ).
- [x] Have a test_Emigration.py
- [x] Add implementation into test_pipeline.py
- [x] Run in notebook pipeline with Fertility and Mortality

**Comment by kasra-hosseini** [comment]
Notebook is still being tested, but it should be finished by tomorrow (running all components).
