### ISSUE TITLE
Build an Immigration module 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/vivarium_population_spenser#29]
- [x] Implement immigration a new component. This could be deterministic and rules based, but we are also free to explore other forms (equivalent to the Fertility module).
- [x] Add test_immigration.py
- [x] Add component to test_pipeline.py
- [x] Run in notebook pipeline with ~Fertility and~ Mortality (removed fertility for computational reasons, maybe we can test this later when all components are in place)

**Comment by crangelsmith** [comment]
Hi @kasra-hosseini , just to let you know (and avoid duplicating work) that the function to compute migration rates developed in PR #32 should work for both the emigration rates and immigration rates.

**Comment by kasra-hosseini** [comment]
Hi @crangelsmith, great! Thanks! I am reviewing the PR now.

**Comment by kasra-hosseini** [comment]
Branch: feature/29-build-an-immigration

**Comment by kasra-hosseini** [comment]
Hi again @crangelsmith , I used your code to plot the migration rates and here is a plot:

<img width="978" alt="Screenshot 2020-07-20 at 16 45 12" src="https://user-images.githubusercontent.com/1899856/87957607-65d51000-caa8-11ea-8042-d2fd45bb4d90.png">

To reproduce:

```python
# Population (total)
plt.figure(figsize=(15, 10))
plt.plot(asfr_data_emigration["age_start"], 
         asfr_data_emigration["mean_value"], 
         '.', c='k', lw=4, markersize=12)
plt.xlabel("Age", size=32)
plt.ylabel("Migration rate", size=32)
plt.xticks(size=24, rotation=90)
plt.yticks(size=24)
plt.grid()
plt.show()
```

I am wondering if the large values at older ages are expected?

**Comment by crangelsmith** [comment]
Hi @kasra-hosseini , thanks for spotting this! I did some checks and I think this is a product of categories with very low statistics, where the predicted number of migrants is higher that the total number of people in that area. I found this particular case:

- Age 88-89
- Ethnicity 'BAN'
- Expected migrants from data: 0.52
- Total population in that category: 0.15
- Ratio: 3.5

I guess we will have to cater for this scenarios, let's discuss with Nik tomorrow about it.

**Comment by kasra-hosseini** [comment]
Hi @crangelsmith Sounds good and thanks for checking. I also implemented the very first version of the immigration component. It is deterministic now in the sense that the total number of immigrants should be specified a priori. Then, at each time step, we sample from the migration rates to assign age/gender/... to the new immigrants. Here is one output example in which:

- the total start population is 1000
- immigrant in one year 100
- mortality rate as before 

(no fertility)

<img width="1010" alt="Screenshot 2020-07-21 at 12 01 17" src="https://user-images.githubusercontent.com/1899856/88047685-e861dc00-cb49-11ea-8ba6-a6d105d39321.png">

**Comment by kasra-hosseini** [comment]
I still need to review and add the `test_immigration.py`. Once these are finished, I will send a PR.

**Comment by kasra-hosseini** [comment]
See PR: https://github.com/alan-turing-institute/vivarium_public_health_spenser/pull/34
