### ISSUE TITLE
Implement a simple Migration module and add a test_migration.py

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/vivarium_population_spenser#3]
Meta-issue, see #29, #28 and #27 

- [x] Understand the numbers of immigration and emigration from data (convert to rates)
- [x] Start from the Mortality component and write a new Migration component that implements emigration (first).
- [x] Have a test_migration.py
- [x] Implement inmigration the new Migration componen (deterministic and rules based).
- [x] Include Migration on test_pipeline.py and notebook pipeline.

**Comment by kasra-hosseini** [comment]
It seems this issue is also finished in PR https://github.com/alan-turing-institute/vivarium_public_health_spenser/pull/33
