### ISSUE TITLE
Integrate Immigration and Emigration together in pipelines

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/vivarium_population_spenser#36]
- [x] Implement Immigration to test_pipeline.py (most of it is already implemented on PR #28 but there are some issues).
- [x] Implement Immigration and Emigration in the notebook pipelines with the full datasets.
- [x] Run all components together (Mortality, Fertility, Immigration, Emigration)

**Comment by kasra-hosseini** [comment]
@crangelsmith while reviewing PR #33, I started working on this issue as well, and now we have both immigration and emigration in `test_pipeline.py`. I also created a new notebook including all components. I am doing some final tests and will send the changes directory to https://github.com/alan-turing-institute/vivarium_public_health_spenser/pull/33.

Also, for tomorrow, I will run the notebook on the whole dataset (using all components), will push the notebook once the results are ready.

**Comment by kasra-hosseini** [comment]
Done. See PR #33 .
