### ISSUE TITLE
Aggregate over 75 for emigration rates

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/vivarium_population_spenser#39]

**Comment by kasra-hosseini** [comment]
@crangelsmith Two more points about emigration.

1) The emigration curve is non-linear (which can be correct), but it would be good to confirm this (see notebook 5):

<img width="1475" alt="Screenshot 2020-07-22 at 10 26 16" src="https://user-images.githubusercontent.com/1899856/88159965-efe6bb00-cc05-11ea-8763-1aa4c696ae70.png">

2) Emigration has very high values at the first time-steps (see the absolute values in the beginning):

<img width="1475" alt="Screenshot 2020-07-22 at 10 28 23" src="https://user-images.githubusercontent.com/1899856/88160118-21f81d00-cc06-11ea-8cba-65b69da3c96f.png">

To clarify, the first figure was generated by:

```python
plt.figure(figsize=(15, 10))
plt.plot(time_axis, emig_pop_axis - emig_pop_axis[0], 
         c='k', lw=4
         #marker="o"
        )
plt.xlabel("Time", size=32)
plt.ylabel("Emigrated", size=32)
plt.xticks(size=24, rotation=90)
plt.yticks(size=24)
plt.grid()
plt.show()
```

and the second figure:

```python
plt.figure(figsize=(15, 10))
plt.plot(time_axis, emig_pop_axis, 
         c='k', lw=4
         #marker="o"
        )
plt.xlabel("Time", size=32)
plt.ylabel("Emigrated", size=32)
plt.xticks(size=24, rotation=90)
plt.yticks(size=24)
plt.grid()
plt.show()
```
